psa_builder.py

The default timeout (2.0s) is too short when working with slower networks, which makes the building process fail when trying to download CMSIS.

Increase GET timeout in fetch_extract_cmsis_pack() in psa_builder.py

---

build_psa_compliance.py

Make sure the prerequisites required for Firmware Framework tests
are executed only with python3.
Fixes #32

Firmware Framework test - python3 support only

---

test_psa_target.py

`test_psa_target.py` can be used to build a target for Regression and
PSA compliance tests.
This can be useful for CI or local development or test PR before the merge.

Support build only option for target

---

build_tfm.py
psa_builder.py

TF-M needs more repos cloned now. This will help us when we update TF-M to a newer version
Tested by successfully building for MUSCA B1 and verifying that the new repos were cloned.
`python3 build_tfm.py -m ARM_MUSCA_B1 -t GNUARM -c ConfigRegressionIPC.cmake`

Clone more repos

---

test/logs/ARM_MUSCA_B1/REGRESSION.log

SST test has been renamed to PS test as part of the TF-M 1.1 release.
This supports `test_psa_target.py` when it compares test results.

Update `ARM_MUSCA_B1` regression test log

---

build_psa_compliance.py
psa_builder.py

Use provided TF-M mbed-crypto interface when building PSA compliance
crypto test suite.
As part of TF-M v1.1 upgrade, it was observed, that additional PSA
compliance crypto tests were failing. Therefore its ideal to use TF-M
provided interfaces to have a synchronization towards different
versions used.

PSA Compliance script update

---

README.md
test/logs/ARM_MUSCA_B1/INTERNAL_TRUSTED_STORAGE.log
test/logs/ARM_MUSCA_B1/STORAGE.log

PSA Compliance (ITS and STORAGE) and Regression test suite runs storage
tests with the different combination of parameters which produces
unpredictable behavior results.
This is mainly because of the following:
* PSA Compliance uses 2 WRITE_ONCE_UID with different size/data/flags
* Regression use a WRITE_ONCE_UID with different size/data/flags
So if, Regression was executed first then PSA compliance
(ITS and STORAGE) test suite would fail and vice-versa.
The way to work around this problem is to erase ITS storage before we
run any test suite, but that introduces wearing out flash storage.
Therefore it is necessary to document the flow of execution to avoid
unpredictable behavior by the following steps:
* Run Regression test
* Run PSA Compliance test suites
The compare logs for …

Update storage test log for `ARM_MUSCA_B1`

---

psa_builder.py
test_psa_target.py
vagrant/bootstrap.sh

Its been observed when executing test suites for target `ARM_MUSCA_B1`
requires an Internal trusted storage (ITS) erase to avoid unpredicated behavior.
Fixes #43

Erase flash area by `srec_cat`

---

README.md
build_psa_compliance.py
mbed_app.json
tfm_ns_import.yaml

`CY8CKIT_064S2_4343W` target is not supported in Mbed OS, therefore removing it.
Fixes #11

Remove Cypress target

---

vagrant/Vagrantfile
vagrant/bootstrap-user.sh

The default Python shipped with Ubuntu Bionic (18.04) is 3.6, but the _latest_ "python3-pip" package from Ubuntu's apt repo only works with 3.7 or newer. Even if we manually configure it to 3.7 or 3.8, we still have other Python issues, possibly due to 3.6 preexisting packages in the system.
This PR simply switches to Ubuntu Focal (20.04) which is the latest LTS. It also installs Mbed CLI dependencies listed in `mbed-os/requirements.txt`.

Vagrant: fix broken dependencies

---

.travis.yml

Fixes: #36
For now, build regression and compliance tests for ARM_MUSCA_S1 and ARM_MUSCA_B1 targets.
Since there are a number of regression tests and compliance tests to build (rather than just one or two), we use the existing `test_psa_target.py` to automate them. Note that this script doesn't support choosing from release/develop/debug profiles yet.

Add Travis job to build all compliance and regression tests

---

build_psa_compliance.py

Fixes: #54
Without passing the toolchain, the default toolchain GNUARM gets selected, making it impossible to build the PSA Compliance test
with ARMCLANG.
The fix is provided by @ccli8, many thanks for that.
I've manually verified it. It won't be covered by the CI which doesn't have the Arm Compiler yet.

build_psa_compliance.py: pass toolchain

---

mbed_app.json

Fixes: #52 
Mbed applications, including the regression tests triggered by `main()`, are run on the non-secure sides. In Mbed OS we only [enable the non-secure timer](https://github.com/ARMmbed/mbed-os/blob/mbed-os-6.5.0/targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/device/device_cfg.h#L47-L50). However, [`plat_test.c`](https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/tree/platform/ext/target/musca_b1/plat_test.c?h=TF-Mv1.1) in trusted-firmware-m defines tests for both secure and non-secure timers. The secure timer tests are *not* eventually used by the final application, and the GCC's linker handles this to links successfully.
But it's a known behaviour that the Arm Compiler's linker (armlink) does not resolve undefined-but-unused symbols, and it fails to link the tests and complains …

Workaround for regression test build with ARMCLANG

---

build_psa_compliance.py

The PSA libraries should be `*.a` for GCC and `*.ar` for the Arm toolchain, in order for them to be linked to the Mbed application. (Those extensions are coded in the Mbed CLI.) They should be copied into corresponding `TOOLCHAIN_*/`.
This fixes linking failure of the PSA Compliance test (undefined symbol "val_entry") with the Arm toolchain, when compiling the Mbed application with compliance tests enabled.

Copy PSA libraries depending on toolchains

---

.github/workflows/main.yml
psa_builder.py

@ARMmbed/mbed-os-security 
Without catching this exception, `are_dependencies_installed()` won't have a chance to print a message before the script crashes.

psa_builder.py: catch command not found error

---

vagrant/bootstrap-user.sh

We are supporting `TF-M v1.1`, due to recent changes in the build
system of TF-M repository, the instructions mentioned in the
vagrant/README.md will not work.
Therefore clone specific tag which supports a working version.

vagrant: clone specific TF-M version tag

---

psa_builder.py

`dev/feature_dualcore` branch is a confusing name to which
Mbed OS + TFM version it supports. Therefore use the right naming
convention by using `mbed-tfm-1.1` instead.

Switch to using `mbed-tfm-1.1`

---

psa_builder.py

Use a specific version of tf-m-tests repository to avoid confusion
on TF-M v1.1 + Mbed OS integration regression tests support.

Switch to using `mbed-tfm-1.1` for tf-m-tests

---

.travis.yml
build_tfm.py
test/logs/ARM_MUSCA_B1/REGRESSION.log
test/logs/ARM_MUSCA_S1/REGRESSION.log
tfm_ns_import.yaml

Preceding PRs: https://github.com/ARMmbed/trusted-firmware-m/pull/13 and https://github.com/ARMmbed/trusted-firmware-m/pull/12
This PR:
* Updates `tfm_ns_import.yaml` and `build_tfm.py` to copy libraries required by regression tests
* Updates regression tests log for ARM_MUSCA_B1 and ARM_MUSCA_S1

Update support for regression tests

---

README.md
test_psa_target.py

restructured to do:
- Build and create test_spec.json
- Run greentea
Why:
This utility script is repeating functionalities in greentea for generating test results. With greentea, we already have results in multiple formats and other features like parallelising tests (say you have multiple devices).

generate test spec for greentea

---

README.md
main.cpp
mbed_app.json
test_psa_target.py

In a standard Greentea test setup, the host sends a sync signal to the target to start the test. This helps to avoid synchronisation issues, e.g. test already running before the host is ready.
To enable this, set "wait-for-sync" to 1 in `mbed_app.json`, or pass `--sync` to `test_psa_target.py`.
Note: Images built this way will NOT start tests on its own - they need to be driven by the Greentea host tools.
Log:
```
[1612528946.71][CONN][RXD] Booting TFM v1.1                                                              
[1612528946.71][CONN][RXD] Waiting for Greentea host      
[1612528946.71][CONN][RXD] mbedmbedmbedmbedmbedmbedmbedmbed                     
[1612528946.72][CONN][RXD] Starting TF-M regression tests                                                
[1612528946.72][CONN][INF] …
```

Enable sync for Greentea test framework

---

README.md
main.cpp
psa_builder.py
test_psa_target.py

Issue: ARM-software/psa-arch-tests#252
Some test cases of the Crypto suite are known to crash during runs. This causes the Greentea test framework to lose synchronization, and messes up the memory and prevents subsequent suites from running There's currently no option in psa-arch-tests to skip known failures. So we exclude the Crypto suite from Greentea runs. Users can still run the Crypto suite manually without automation.
Additionally, this PR adds an option `-r/--run-only` to `test_psa_target.py`. It also improves code readability as @saheerb raised in https://github.com/ARMmbed/mbed-os-tf-m-regression-tests/pull/74#discussion_r572919443.
Crypto Test failure - https://developer.trustedfirmware.org/T865

Exclude the Crypto suite from the Greentea test spec

---

README.md
vagrant/README.md
vagrant/bootstrap-user.sh
vagrant/bootstrap.sh

To minimise the maintenance effort, we've decided that the Vagrant virtual machine should only provide an environment. This PR
* removes the fetching of TF-M related repositories from the scripts
* removes instructions to build the vanilla TF-M
* adds more info on how to use the virtual machine
* adds `ninja-build` to the script, as we use Ninja to speed up TF-M v1.2 build
Tested on Musca S1.

Update Vagrant scripts and instructions

---

.gitignore
build_tfm.py
ci_scripts/check_rebase.py
psa_builder.py

Mbed OS needs some additional patches to use a TF-M release.
The objective of this script is to rebase those Mbed OS patches onto
latest external TF-M version, this ensures the effectiveness of future
Mbed OS (patches) + TF-M (latest) integration work.
These are the steps performed by the script:
* Clone `upstream-tfm` repositories
* Checkout `mbed-tfm` repositories (these contain Mbed OS patches)
* Perform rebase operation

Check rebase script

---

build_tfm.py

The path in a commit message auto-generated by `--commit` should be relative to `mbed-os`.

Fix path in commit message generated by `--commit`

---

build_tfm.py
ci_scripts/check_rebase.py
psa_builder.py

Fixes #24
The issue on Windows (Host OS) is that it clones dependencies in
read-only mode, which creates an issue when deleting them if
`test_psa_target.py` or `build_tfm.py` is executed.
Therefore handle the permission issue by setting them in read-write
mode.

Fix read permission error on host OS

---

VERSION.txt
build_tfm.py
ci_scripts/build_external_tfm.py
ci_scripts/check_rebase.py
psa_builder.py
test_psa_target.py

This enables the building of TF-M latest config which was set up by `check_rebase.py`.
`build_external_tfm.py` builds `ARM_MUSCA_S1` target with the external TF-M + patches required by Mbed OS. It relies on `check_rebase.py` to set up the required dependencies.

Add new functionality to `build_tfm.py` 

---

test_psa_target.py

Relative paths allow users to build tests in a VM/container and run them in a host without worrying about paths.

Use relative paths in Greentea test_spec.json

---

.github/workflows/main.yml
build_tfm.py
psa_builder.py

Previous, python format checks was not enabled for the branch tf-m-v1.2-integration. This lead to a few format issues.
This PR fixes the formats, and enables the check globally for all branches.

Fix python formats and enable checks on all branches

---

build_tfm.py

This PR is to address #85 and supports multi-level TF-M target name say `nuvoton/m2354`. It fixes generated TF-M `s_veneers.o` copy path.

Support multi-level TF-M target name

---

.travis.yml

The TF-M v1.2 integration work has been merged to the master branch of Mbed OS: https://github.com/ARMmbed/mbed-os/pull/14354
Now it's time to switch the branch back in Travis.

.travis.yml: use the master branch of mbed-os

---

psa_builder.py

The PSA Crypto API on the master branch of psa-arch-tests has been updated to 1.0.0 but TF-M only support version 1.0-beta-3 of this API, as of the time of this commit. We need to use the tag ["Before_Crypto_1.0"](https://github.com/ARM-software/psa-arch-tests/releases/tag/Before_Crypto_1.0) from the psa-arch-tests repository.

Use a fixed version of psa-arch-tests

---

.circleci/config.yml
.travis.yml
CMakeLists.txt
README.md
build_tfm.py
psa_builder.py
test_psa_target.py
vagrant/bootstrap-user.sh
vagrant/bootstrap.sh

This PR
* adds `CMakeLists.txt` to support Mbed CLI 2
* adds an option `--cli=[1|2]` to `test_psa_target.py` to select the Mbed CLI version (defaults to **2** if unspecified)
* updates `README.md` to document the use of Mbed CLI 2
* updates the Travis configurations to use Mbed CLI 2
* adds a CircleCI configuration to test Mbed CLI 1 build - CircleCI is used for consistency with all Mbed OS examples
Note: This PR is able to compile on its own. To be able to run it on an actual target, your check-out of mbed-os needs to have https://github.com/ARMmbed/mbed-os/pull/14361.

Support Mbed CLI 2

---

test_psa_target.py

The `mbedgt` command allows users to run a single test suite using the `-n` option. But it has a limitation/bug that the test names in `test_spec.json` must be in lower case, otherwise the user-specified case cannot be found.
The test names passed by the user via `-n` can be in upper or lower case - `mbedgt` converts them to lower case.

Use lower case test names in test_spec.json

---

.circleci/config.yml
.travis.yml
CMakeLists.txt
build_tfm.py
main.cpp
tfm_ns_import.yaml

This PR
* ~enables the IPC suites for Musca S1 (whose support was supported recently)~
Note: temporarily _disabled_ again, as it can't run due to an issue in MRAM fast-read...
* switches to fetch vanilla TF-M
* updates the list of test files
* disables unsupported IRQ tests (not supported for by TF-M in PSA mode anymore)
Notes:
* Preceding PR: https://github.com/ARMmbed/mbed-os/pull/14396 (merged)
* This is _not_ compatible with the current TF-M v1.2, which is why we have a separate branch. Once TF-M v1.3 is released, we will then be able to merge this to the master branch.

CI branch to integrate the latest vanilla TF-M with Mbed OS

---

main.cpp

The timeout set in the application is sent to the Greentea test host, becoming the maximum number of seconds the host will wait before getting expected test results.
Currently TF-M Regression and PSA Compliance tests take less than 20 seconds each, so there is no point waiting 600 seconds. The reduced timeout is still sufficient and speeds up retries (if enabled).
Note: The intention is use `--retry-count` in CI as storage on Musca S1 is sometimes unstable. It's not added to this PR because it may not be needed on local boards.

Reduce test timeout to 90 seconds

---

README.md
build_tfm.py
psa_builder.py
test/logs/ARM_MUSCA_S1/IPC.log
test_psa_target.py

Fixes: #49 
Support for the PSA IPC suite on Musca S1 has recently been added to trusted-firmware-m and psa-arch-tests. This PR enables it on the _latest TF-M_ + Mbed OS continuous integration branch whose commits will be eventually used for TF-M v1.3.
@ARMmbed/mbed-os-core

Enable the PSA IPC suite on Musca S1

---

build_tfm.py
psa_builder.py
tfm_ns_import.yaml

This PR does the following:
* Use trusted-firmware-m's own version control - The build system of trusted-firmware-m tracks specific versions of dependencies. This _fixes our nightly CI failure_ due to the latest psa-arch-tests not compiling with the latest trusted-firmware-m.
* Clean up version tracking of trusted-firmware-m - Now the only thing to fetch is https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git. Note: Not backward compatible with TF-M v1.2, but the tfm_latest_integration_check branch is CI-only, and some other parts of the scripts on this branch don't work with TF-M v1.2 anyway. The current master branch is for production and works with TF-M v1.2.
* Handle switching of git remote - We renamed remotes in the previous commit and a few times before, but the failure (due …

Refactor fetching of trusted-firmware-m

---

vagrant/bootstrap-user.sh
vagrant/bootstrap.sh

The latest version of cryptography requires Rust to be installed and is
not guaranteed to work with other Ubuntu compatible python packages.
Instead we should use the version of cryptography from the Ubuntu
package registry, as that version has been verified to work on the
version of Ubuntu used in vagrant.

vagrant: Use cryptography from Ubuntu package registry

---

build_tfm.py
tfm_ns_import.yaml

The branch [tfm_latest_integration_check](https://github.com/ARMmbed/mbed-os-tf-m-regression-tests/tree/tfm_latest_integration_check) serves to test the latest development version (the master branch) of TF-M against Mbed OS, enabling us to perform any integration work early before the next release.
As a result of the branch switch, the locations of some of the files to import from TF-M have changed and this PR also updates the list.

Use the latest TF-M for continuous integration

---

test/logs/ARM_MUSCA_B1/REGRESSION.log

The PSA Firmware Update (FWU) API and tests are available on Musca B1.
Without this change the Greentea test runner still treats the tests as a pass as long as the other lines match the serial output, but we add it for completeness.

Musca B1: Add firmware update to Regression test log

---

test/logs/ARM_MUSCA_B1/REGRESSION.log
test/logs/ARM_MUSCA_S1/REGRESSION.log

The latest TF-M has renamed the identifier of each test suite.
This fixes the regression tests in the nightly CI for the latest development version of TF-M + Mbed OS.

Update TF-M Regression Tests logs

---

tfm_ns_import.yaml

The path containing the library tfm_test_suite_fwu_ns has been moved in tf-m-tests.

Update path to libtfm_test_suite_fwu_ns.a

---

.mbedignore
build_tfm.py

This PR fixes the following:
* _CI BRANCH ONLY: Workaround for renamed Musca targets_: The latest development version of TF-M has moved "musca_s1" and "musca_b" into the "arm" subdirectory which becomes part of the target names. But `tfm_target_name`s in `targets.json` of Mbed OS track the released version of TF-M (v1.3.0 at this point).
The temporary workaround is to hardcode the values in `build_tfm.py` on the tfm_latest_integration_check branch to unblock nightly CI. This will be removed when the next TF-M release becomes available and we update `targets.json` in Mbed OS.
* _Mbed CLI 1: Ignore Mbed TLS source_: The PSA headers from trusted-firmware-m are not currently fully compatible with the Mbed TLS source code, lacking some definitions in crypto headers. Normally, when we upgrade …

Workarounds for renamed Musca targets, Mbed CLI 1 failure

---

.mbedignore
psa_builder.py

* Work around Mbed CLI 1 build error, due to PSA header incompatibility with Mbed TLS. Cherry picked from 564233bff389d9db6be5b2b0065de54c761dedce on the tfm_latest_integration_check branch.
* Drop the requirement of "make", as we now use "ninja" as the CMake generator.

Workaround Mbed CLI 1 build, drop requirement of "make"

---

CMakeLists.txt

Requires: https://github.com/ARMmbed/mbed-os/pull/14880
The test application uses the greentea client for synchronization with the host and unity for assertions, and unity in Mbed OS contains references to utest. We have recently split them from one mbed-greentea library into three, so the test application needs to link all of them.
Notes:
* The communication between device and host does not currently work, because currently the integration of [greentea-client](https://github.com/ARMmbed/greentea-client) + Mbed OS has an I/O issue. Nonetheless, it does not affect this PR because the version of greentea-client is controlled by Mbed OS which we always use the latest version of.
* Once this gets in, we need to rebase the branch tfm_latest_integration_check to take advantage of the fix too.

CMake: Fix linking of greentea, unity and utest

---

CMakeLists.txt
README.md
test/logs/ARM_MUSCA_B1/CRYPTO.log
test/logs/ARM_MUSCA_B1/REGRESSION.log
test/logs/ARM_MUSCA_S1/CRYPTO.log
test/logs/ARM_MUSCA_S1/REGRESSION.log
test_psa_target.py
tfm_ns_import.yaml

* _Update the list of files to import from TF-M_: Some file locations have changed in the latest development branch of TF-M.
* _Enable the Crypto suite_: The Crypto suite was disabled due to crashes that made tests unable to continue. With the latest TF-M and psa-arch-tests, it doesn't crash anymore so we can re-enable it with updated number of expected failures.
* _Fix REGRESSION.log format_: The TF-M Regression tests recently have printing fixed - now "has" and "PASSED" have exactly one space in-between instead of two.

Update the list of files to import, enable PSA Crypto suite

---

tfm_ns_import.yaml

This PR tries to add missing IPC file for PSA Firmware Update. It address #120.

Add missing IPC file for PSA Firmware Update

---

.circleci/config.yml
.travis.yml
CMakeLists.txt
README.md
build_tfm.py
psa_builder.py
test/logs/NU_M2354/REGRESSION.log
test_psa_target.py
tfm_ns_import.yaml

This PR tries to upstream M2354 port to mainstream. It includes:
1.  Change trusted-firmware-m download path to Nuvoton forked repository (`nuvoton_mbed_m2354_tfm-1.3`) for M2354
1.  Add post-build copy paths specific to M2354 (`tfm_ns_import.yaml`)
1.  Detect python/python3 command name across platforms
1.  Enable Mbed CLI 2 (CMake)
1.  Enable Greentea test path
1. Disable PSA compliance test, which M2354 hasn't supported yet
1. Add compare log (REGRESSION.log only)
**NOTE1**: For upgrade to TF-M 1.4 for M2354, change branch to `nuvoton_mbed_m2354_tfm-1.4`.
**NOTE2**: About GCC toolchain, 9 2020-q2-update (and earlier)/10-2020-q4-major have issues on [-Os](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95646)/[-mcmse](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99157) respectively. This …

M2354: Support Nuvoton M2354

---

tfm_ns_import.yaml

This PR, reflecting https://github.com/ARMmbed/mbed-os/pull/15029, adds `partition_M2354.h` into TF-M import list

M2354: Add TF-M import partition_M2354.h

---

build_tfm.py

The build_tfm script can automatically commit the TF-M secure binaries
and source code to the mbed-os repository. Previously the commit
messages it created all began with "Updated ..." which is bad style for
a commit message subject line. We should use imperative mood rather than
indicative mood.

build_tfm: Use imperative mood for commit messages

---

CMakeLists.txt
README.md
mbed-os.lib
psa_builder.py
test/logs/ARM_MUSCA_B1/CRYPTO.log
test/logs/ARM_MUSCA_B1/REGRESSION.log
test/logs/ARM_MUSCA_S1/CRYPTO.log
test/logs/ARM_MUSCA_S1/REGRESSION.log
test/logs/NU_M2354/REGRESSION.log
test_psa_target.py
tfm_ns_import.yaml

Update TF-M to v1.4.0.
Note, this PR depends on https://github.com/ARMmbed/mbed-os/pull/15050, as this PR removes the workaround for the directory change upstream for musca targets.

Update to TF-M v1.4.0

---

mbed-os.lib

Revert accidentally merged temporary commit used for testing. We'd like
to use vanilla mbed-os from now on instead.
This reverts commit 71ff44ddc564a5d67a0cf94067045f003fd1352f.

Revert "TEMP_COMMIT: point to mbed-os PR"
